---
abstract: 'Persist multiple trees in a single db table, preserving child order'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '1.001014'
configure_requires:
  Module::Build: '0.4211'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tree-DAG_Node-Persist
provides:
  Tree::DAG_Node::Persist:
    file: lib/Tree/DAG_Node/Persist.pm
    version: '1.08'
  Tree::DAG_Node::Persist::Create:
    file: lib/Tree/DAG_Node/Persist/Create.pm
    version: '1.08'
requires:
  DBD::SQLite: '1.46'
  DBI: '1.633'
  DBIx::Admin::CreateTable: '2.1'
  File::Temp: '0'
  Getopt::Long: '2.42'
  Hash::FieldHash: '0.14'
  Pod::Usage: '1.65'
  Scalar::Util: '1.41'
  Tree::DAG_Node: '1.24'
  strict: '0'
  warnings: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '1.08'
