---
abstract: 'Persist multiple trees in a single db table, preserving child order'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::Pod: 1.41
  Test::Simple: 0.94
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-DAG_Node-Persist
provides:
  Tree::DAG_Node::Persist:
    file: lib/Tree/DAG_Node/Persist.pm
    version: 1.00
requires:
  DBD::SQLite: 1.29
  DBI: 1.611
  DBIx::Admin::CreateTable: 2.04
  File::Temp: 0.22
  Hash::FieldHash: 0.1
  Scalar::Util: 1.23
  Tree::DAG_Node: 1.06
  common::sense: 3
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.00
